### ISSUE TITLE
PrintSVA datatypes 

### ISSUE THREAD

**Issue by aashildl** [ludwig247/DeSCAM#15]
The macro functions in PrintSVA use types that do not exist in SV (boolean, unsigned[31:0]).
The functions printed in the file *_functions.sva uses bool instead of boolean, but bool is also not an SV type.

Consider using the SV types
- bit (2-state), logic (4-state) instead of boolean and bool
- int (2-state), integer (4-state) or bit/logic[31:0] unsigned instead of unsigned[31:0]

**Comment by ludwig247** [comment]
@aashildl does this affect only the functions generated from SystemsC or does it affect also the visible registers?
