### ISSUE TITLE
PrintSVA functions syntax error

### ISSUE THREAD

**Issue by aashildl** [ludwig247/DeSCAM#16]
The PrintSVA plugin prints "end" after return statements for the functions in the *_functions.sva file, which is not correct SV syntax.

**Comment by ludwig247** [comment]
fixed. if it works please close the issue

**Comment by aashildl** [comment]
PrintSkeleton does not compile for branch deprecated with error message 'class SCAM::State has no member named 'getOutgoingOperationsList' on line 422.

**Comment by ludwig247** [comment]
Is this working for you?

**Comment by aashildl** [comment]
Yes, it works
