### ISSUE TITLE
duplicated optimized functions

### ISSUE THREAD

**Issue by ludwig247** [ludwig247/DeSCAM#21]
@mi-alkoudsi 

For example running TestFunction0 with optimizations creates 3 new functions. 

All of them are equivalent (at least to my awareness). If there is nothing to optimize you should use the original function. 

        macro foo_opt1(x: signed) : signed :=
        	if (not((x <= resize(4,32)))) then signed((shift_left((x + resize(1,32))(31 downto 0),resize(1,32))))
        	elsif ((x <= resize(4,32)) and not((x <= resize(19,32)))) then signed((resize(3,32) + x)(31 downto 0))
        	elsif ((x <= resize(4,32)) and (x <= resize(19,32)) and (x = resize(19,32))) then signed((x + resize(1,32))(31 downto 0))
        	else signed(resize(0,32))
        end if;
        end macro;

        macro foo_opt2(x: signed) : signed :=
        	if (not((x <= resize(4,32)))) then signed((shift_left((x + resize(1,32))(31 downto 0),resize(1,32))))
        	elsif ((x <= resize(4,32)) and not((x <= resize(19,32)))) then signed((resize(3,32) + x)(31 downto 0))
        	elsif ((x <= resize(4,32)) and (x <= resize(19,32)) and (x = resize(19,32))) then signed((x + resize(1,32))(31 downto 0))
        	else signed(resize(0,32))
        end if;
        end macro;

        macro foo_opt3(x: signed) : signed :=
        	if (not((x <= resize(4,32)))) then signed((shift_left((x + resize(1,32))(31 downto 0),resize(1,32))))
        	elsif ((x <= resize(4,32)) and not((x <= resize(19,32)))) then signed((resize(3,32) + x)(31 downto 0))
        	elsif ((x <= resize(4,32)) and (x <= resize(19,32)) and (x = resize(19,32))) then signed((x + resize(1,32))(31 downto 0))
        	else signed(resize(0,32))
        end if;
        end macro;

**Comment by mi-alkoudsi** [comment]
@ludwig247 
Yes, you are right.
This will be solved with the next pull request.
