### ISSUE TITLE
Incorrect name in installation script

### ISSUE THREAD

**Issue by jschauss** [ludwig247/DeSCAM#24]
In the installation script install_new.sh in line 88 the target name should have the same name as in the CMakeList

`$CMAKE_BIN --build $SCAM_HOME/install/tmp/build/ --target SCAM -- -j 4`

`add_executable(DESCAM main.cpp)` in DeSCAM/src/parser/CMakeLists.txt

Rename SCAM -> DESCAM in installation script

**Comment by ludwig247** [comment]
Thanks. It's fixed !
