### ISSUE TITLE
function _getVariableMap()_ returns removed variables

### ISSUE THREAD

**Issue by jschauss** [ludwig247/DeSCAM#33]
The function _getVariableMap()_ in _./src/model/Module.cpp_ returns variables, which are removed during optimization.

**Example (RISCV_ISA):**
Variables phase, aluOp1, aluOp2, ... are removed during optimization, but if we call the function _getVariableMap()_, it returns phase, aluOp1, aluOp2, ...

**Comment by ludwig247** [comment]
Yes. This is correct and intended behavior. 
If you're looking to find the variables after removing you have to take also into consideration the PropertySuite. getVisibleRegisters provides you all variables that remain in the properties after optimization.
