### ISSUE TITLE
initial value != reset value (Enums)

### ISSUE THREAD

**Issue by jschauss** [ludwig247/DeSCAM#34]
The function _getInitialValue()_ in _./src/model/VariableTemplate_ returns for enum values initial values not equal to the reset values of the Reset Property. The function always return the first value of the enum.

**Example (RISCV_ISA):**
The reset value of the variable _toMemoryPort_sig.mask_ of the Reset Property is MT_W while the function _getInitialValue()_ returns MT_B

**Comment by ludwig247** [comment]
Side node: sometimes the value after reset is given be the path leading to the first state
