### ISSUE TITLE
Error when comparing unsigned int to 0

### ISSUE THREAD

**Issue by aashildl** [ludwig247/DeSCAM#38]
When comparing `suspending_count`, and unsigned int, to 0, DeSCAM gives the following error:
`(or control_in_dataXYZ_active
    (not (= update_suspending_count_function_1 #x00000000)))
update_suspending_count(control_in_sig[active],suspending_count)unsigned==0int
Relational: RHS(int) and LHS(unsigned) are not of the same datatype
0
terminate called after throwing an instance of 'std::runtime_error'
  what():  update_suspending_count(control_in_sig[active],suspending_count)unsigned==0int
Relational: RHS(int) and LHS(unsigned) are not of the same datatype`

The line causing the error:
`else if (!rx_bit && (control_req.active || suspending_count > 0))`

**Comment by ludwig247** [comment]
I fixed this issues on the current feature-branch: feature-global-functions. 

As soon as I merge it is going to work.
