### ISSUE TITLE
array types are seen as compound types in property macros

### ISSUE THREAD

**Issue by jschauss** [ludwig247/DeSCAM#41]
The function `isCompoundType()` of the `PropertyMacro` class is always true for compound types AND array types. The function `isArrayType()` is never true, neither for array types nor for compound types. 

-> There is no distinction between array types and compound types

Can be tested with the **RISCV_ISA (Array)** example.

**Comment by ludwig247** [comment]
macro fromRegsPort_sig : unsigned_32 := end macro;
------------> delete 
macro fromRegsPort_sig_0 : unsigned := end macro;
macro fromRegsPort_sig_1 : unsigned := end macro;
macro fromRegsPort_sig_10 : unsigned := end macro;
macro fromRegsPort_sig_11 : unsigned := end macro;
macro fromRegsPort_sig_12 : unsigned := end macro;
macro fromRegsPort_sig_13 : unsigned := end macro;
macro fromRegsPort_sig_14 : unsigned := end macro;
macro fromRegsPort_sig_15 : unsigned := end macro;
macro fromRegsPort_sig_16 : unsigned := end macro;
macro fromRegsPort_sig_17 : unsigned := end macro;
macro fromRegsPort_sig_18 : unsigned := end macro;
macro fromRegsPort_sig_19 : unsigned := end macro;
macro fromRegsPort_sig_2 : unsigned := end macro;
macro fromRegsPort_sig_20 : unsigned := end macro;
macro fromRegsPort_sig_21 : unsigned := end macro;
macro fromRegsPort_sig_22 : unsigned := end macro;
macro fromRegsPort_sig_23 : unsigned := end macro;
macro fromRegsPort_sig_24 : unsigned := end macro;
macro fromRegsPort_sig_25 : unsigned := end macro;
macro fromRegsPort_sig_26 : unsigned := end macro;
macro fromRegsPort_sig_27 : unsigned := end macro;
macro fromRegsPort_sig_28 : unsigned := end macro;
macro fromRegsPort_sig_29 : unsigned := end macro;
macro fromRegsPort_sig_3 : unsigned := end macro;
macro fromRegsPort_sig_30 : unsigned := end macro;
macro fromRegsPort_sig_31 : unsigned := end macro;
macro fromRegsPort_sig_4 : unsigned := end macro;
macro fromRegsPort_sig_5 : unsigned := end macro;
macro fromRegsPort_sig_6 : unsigned := end macro;
macro fromRegsPort_sig_7 : unsigned := end macro;
macro fromRegsPort_sig_8 : unsigned := end macro;
macro fromRegsPort_sig_9 : unsigned := end macro;

**Comment by ludwig247** [comment]
I' will delay this until the new data structure is done next week.

**Comment by ludwig247** [comment]
@jschauss: I think this issue is solved now. 
isArrayType() and isCompoundType() should now be working as expected?
