### ISSUE TITLE
CFGFactory runtime error

### ISSUE THREAD

**Issue by aashildl** [ludwig247/DeSCAM#62]
When running DeSCAM compiled from branch development, the program terminates with the following message:

-E- CFGFactory::translateToScamCFG():  clangCFG is nullterminate called after throwing an instance of 'std::out_of_range'
  what():  map::at

**Comment by ludwig247** [comment]
What file are you running?

**Comment by aashildl** [comment]
Tried with several files, for example example/Bus/ESL/Bus_new.h

**Comment by ludwig247** [comment]
You're running the most current version?

Can you try to clean the project and rebuild from scratch (not reinstall just delete the build files). 

Maybe one of the shared libraries is not recompiled. 

For me everything works (also the two build in GitHub Actions work fine)

**Comment by aashildl** [comment]
I am on the most current version. I tried make clean before make, and also remade the Makefile with cmake. Still get the error, no matter which file I try.

**Comment by ludwig247** [comment]
What Linux are you running? 

I know it sounds crazy but could delete all build-files and also the entire bin folder? 

I just did build everything on our servers to triple check. Bus_new works, as well as the tests. 

I think the problem is somewhere in your setup. Did you move the DeSCAM folder?

**Comment by aashildl** [comment]
I am running Ubuntu 18.04 in WSL. 
I gave in and reinstalled DeSCAM in a new folder. It now works.
