### ISSUE TITLE
Missing bitwise negation print in SVA plugin

### ISSUE THREAD

**Issue by aashildl** [ludwig247/DeSCAM#66]
The bitwise negation operator (`~`) is not printed by the PrintSVA plugin.

Example: 
`error_src = ERROR_MASK(~bus_in_msg.data & error_src);`
results in 
`t_end(o) ##0 error_src == ERROR_MASK(bus_in_msg_data_0 & error_src_0)`

**Comment by ludwig247** [comment]
I'll start working on it tomorrow morning.

**Comment by ludwig247** [comment]
It's fixed :)
