### ISSUE TITLE
disable iff (reset) (SVA)

### ISSUE THREAD

**Issue by tojauch** [ludwig247/DeSCAM#71]
"disable iff (reset)" needs to refer to the actual reset signal from the design (e.g. "bus_new.rst"), otherwise properties will fail spuriously.

**Comment by ludwig247** [comment]
Thanks for the issue. I double checked on this: 
I think the problem was the at the bottom: 

`bind Switch Switch_verification inst (.*, .reset(rst));` 

There is a bind statement. Here it's the designers taks to provide the real name of the reset signal to the Skeleton.
