### ISSUE TITLE
PrintSkeleton Error with arrays

### ISSUE THREAD

**Issue by WezelA** [ludwig247/DeSCAM#8]
If you use an array in SystemC, PrintSkeleton will initialize the array during the reset with the following line:

`buffer_signal <= (others <= to_signed(0, 32));`

which is incorrect syntax due to `<=` after the `others` keyword. It should look like this:

`buffer_signal <= (others => to_signed(0, 32));`

**Comment by ludwig247** [comment]
@WezelA Could you provide an example that causes this issue? 
In the test cases this problem does not show up.

**Comment by WezelA** [comment]
Can't find the test case anymore. Maybe fixed with one of the newer versions?
Issue closed
